vertcoin-project/one-click-miner-vnext

backend/languages.go
frontend/src/i18n/es.json
frontend/src/main.js

Spanish trnslation added. 
Ideally still need feedback from Latin-spanish speaker.

Add spanish translation

---

backend/languages.go
frontend/src/i18n/hr.json
frontend/src/main.js

Added Croatian Language

---

backend/languages.go
frontend/src/i18n/sv.json
frontend/src/main.js

Adding Swedish support

---

backend/languages.go
frontend/src/i18n/sl.json
frontend/src/main.js

Added Slovenian

---

backend/languages.go
frontend/src/i18n/ja.json
frontend/src/main.js

I've lived in Japan for 10 years so my Japanese language skills are native. More commits on the way will make sure the rest will be completed within 24 hours.

Complete Japanese translation for 'generic' and 'welcome'

---

frontend/src/i18n/pl.json

Polish translation

---

backend/languages.go
frontend/src/i18n/zh.json
frontend/src/main.js

Simplified Chinese translation roughly half complete, will complete the other half in 24 hours

Complete Chinese (Simplified) translation

---

frontend/src/i18n/zh.json

I realised I left an English full stop in the "Please enter password" string, fixed.

Left an English full stop between 2 sentences for Chinese translation 

---

backend/languages.go
frontend/src/i18n/hi.json
frontend/src/i18n/pj.json
frontend/src/main.js

Punjabi Translations by SoiledCold

Punjabi Translations 

---

frontend/src/i18n/en.json

[en.json] Correct spelling

---

frontend/src/i18n/sv.json

Added missing obj["generic"]["close"] and obj["welcome"]["alreadyrunning"]

Update issue #40 Swedish

---

README.md
backend/backend.go
backend/settings.go
frontend/src/components/Mining.vue
frontend/src/i18n/en.json
miners/miners.go
pools/hashalot.go
pools/pool.go
pools/zergpool.go

This adds [Zergpool](https://zergpool.com/) in order to help distribute hash rate.

Add Zergpool

---

backend/languages.go
frontend/src/i18n/tr.json
frontend/src/main.js

I translated the software to Turkish language, added the language on backend and frontend files.

Turkish Language

---

frontend/src/i18n/de.json

This commit fixes most of the rather bad German translation

Fixed bad translation

---

networks/ping.go

Added public p2pool nodes vtc-fl.javerity.com (Florida, USA) and vtc-ca.javerity.com (California, USA)

Add 2 p2pool public nodes

---

networks/ping.go

Should I update the number of nodes as well?

Added vtc.p2pminers.nl to public p2pool nodes

---

pools/p2pool.go

This PR fixes a bug in which P2Pool fees were not always being displayed correctly

Fix P2Pool fee

---

frontend/src/i18n/de.json

Include all missing labels from en.json

Update german translations

---

pools/acidpool.go
pools/bbqdroid.go
pools/pool.go
pools/zpool.go

Adds two new pools - BBQDroid.org and Acidpool.co.uk
BBQDroid - KarNaa#9513 on discord.
Acidpool - ASCiiDiTY (acidpool.co.uk)#3647

New pools - BBQDroid.org and Acidpool.co.uk

---

pools/miningpoolsweden.go
pools/pool.go

Add new pool Miningpoolsweden
discord: archen#0837

New pool - Miningpoolsweden

---

pools/bbqdroid.go

Much smaller DB query size and return JSON.
Also update fees to 1% to reflect reality.

Use optimized API for balances.

---

p2pool_nodes.json

This adds the two nodes from PRs #428 and #440 in the JSON file introduced by #420

Add two nodes from PR #428 and #440

---

p2pool_nodes.json

Added my p2pool node to p2pool_nodes.json (lines 52-56).

Added p2pool node for vtc-ut.myangelprints.com:9171
